version: '3'
services:
  rating-simulator:
    container_name: rating-simulator
    # build:
    #     context: .
    #     dockerfile: ./Dockerfile
    image: ghcr.io/distributed-it-for-telco/distributed-rating-demo:latest
    restart: always
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"